# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: yam0x45
email: cb@cambrauner.dev
description: >- # this means to ignore newlines until "baseurl:"
  Hi! I'm Cameron. I'm currently a penetration tester and purple
  teamer. I like to blog about topics I am interested in or currently
  learning about. I received my Bachelors of Science in Cybersecurity
  from the College of Engineering at the University of South Florida.
domain: cambrauner.dev
baseurl: "" # the subpath of your site, e.g. /blog
url: https://cambrauner.dev # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Yam0x45
github_username:  YameronB

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num/"

# jekyll-tagging (optional)
tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# for github pages custom domains:
include: cambrauner.dev

dash:
  # the way how dates should be displayed
  date_format: "%b %-d, %Y"  

  # the animation speed of the post scroll-in effect
  animation_speed: 50

  # wether to enable Right-to-Left support or not
  rtl: false

  # Replaces the default avatar provider (gravatar)
  avatar_source: github
  github_username: YameronB
  #avatar_source: local
  #avatar_path: /assets/avatar.png

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/Yam0x45
      icon: twitter-square
      color: cyan
    - url: https://github.com/YameronB
      icon: github-square
      color: purple
  
  # wether the author box should be displayed or not
  show_author: true
